Traceback (most recent call last):
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 225, in <module>
    scrape_and_save()
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 208, in scrape_and_save
    data = scrape_all()
           ^^^^^^^^^^^^
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 193, in scrape_all
    hall_data = scrape_columbia(hall)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 103, in scrape_columbia
    with managed_webdriver() as driver:
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 87, in managed_webdriver
    service = ChromeService(ChromeDriverManager().install())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\file_manager.py", line 63, in __extract_zip
    archive = zip_class(archive_file.file_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\zipfile.py", line 1284, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\carol\\.wdm\\drivers\\chromedriver\\win64\\130.0.6723.116\\chromedriver-win32.zip'
